trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: SWA-Secrets
- name: build_dir
  value: 'build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build React App'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: '$(build_dir)'
    azure_static_web_apps_api_token: $(deployment_token)
